AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Description: DotnetWebhookGH - PostgreSQL

Resources:

  PostgreSQLInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    Properties:
      DBInstanceIdentifier: dotnet-webhook-gh
      MasterUsername: '{{resolve:secretsmanager:dotnet-webhook-gh/PostgreSQL:SecretString:Username}}'
      MasterUserPassword: '{{resolve:secretsmanager:dotnet-webhook-gh/PostgreSQL:SecretString:Password}}'
      Engine: postgres
      EngineVersion: '14.6'
      PubliclyAccessible: true
      DBInstanceClass: db.t4g.micro
      AllocatedStorage: 20
      StorageType: gp2
      VPCSecurityGroups:
        - sg-013192d48972caa5f
      Tags:
        - Key: app:component
          Value: PostgreSQL
        - Key: app:product
          Value: DotnetWebhookGH
        - Key: app:source
          Value: https://github.com/marxjmoura/dotnet-webhook-gh
